const products = [
  {
    id: 1,
    name: 'Wireless Headphones',
    description: 'High-quality wireless headphones with noise cancellation.',
    price: 99.99,
    category: 'Electronics',
    image: 'client/public/images/wirelessheadphone.jpeg'
  },
  {
    id: 2,
    name: 'Smartwatch',
    description: 'Feature-packed smartwatch with fitness tracking.',
    price: 149.99,
    category: 'Electronics',
    image: 'client/public/images/smartwatch.jpeg',
  },
  {
    id: 3,
    name: 'Running Shoes',
    description: 'Comfortable and durable running shoes for all terrains.',
    price: 89.99,
    category: 'Footwear',
    image: 'client/public/images/runninshoes.jpeg',
  },
  {
    id: 4,
    name: 'Backpack',
    description: 'Spacious and stylish backpack for everyday use.',
    price: 59.99,
    category: 'Accessories',
    image: 'client/public/images/backpack.jpeg',
  },
  {
    id: 5,
    name: 'Water Bottle',
    description: 'Eco-friendly water bottle with a sleek design.',
    price: 19.99,
    category: 'Accessories',
    image: 'client/public/images/waterbottle.jpeg',
  },
  {
    id: 6,
    name: 'Yoga Mat',
    description: 'Non-slip yoga mat for your daily practice.',
    price: 29.99,
    category: 'Fitness',
    image: 'client/public/images/yogamat.jpeg',
  },
  {
    id: 7,
    name: 'Blender',
    description: 'High-speed blender for smoothies and shakes.',
    price: 79.99,
    category: 'Home Appliances',
    image: 'client/public/images/blender.jpeg',
  },
  {
    id: 8,
    name: 'Sunglasses',
    description: 'Stylish sunglasses with UV protection.',
    price: 39.99,
    category: 'Accessories',
    image: 'client/public/images/sunglasses.jpeg',
  },
  {
    id: 9,
    name: 'Laptop Stand',
    description: 'Adjustable laptop stand for better ergonomics.',
    price: 49.99,
    category: 'Office Supplies',
    image: 'client/public/images/laptopstand.jpeg',
  },
  {
    id: 10,
    name: 'Desk Lamp',
    description: 'LED desk lamp with adjustable brightness.',
    price: 24.99,
    category: 'Office Supplies',
    image: 'client/public/images/desklamp.jpeg',
  },
  {
    id: 11,
    name: 'Power Bank',
    description: 'A power bank for charging phones',
    price: 21.99,
    category: 'Accessories',
    image: 'client/public/images/powerbank.jpeg',
  },
  {
    id: 12,
    name: 'Charger',
    description: 'A type C iphone charger.',
    price: 10.99,
    category: 'Accessories',
    image: '../public/images/charger.jpeg',
  }
]
export default products;
